### ISSUE TITLE
i18n: punctuation not preserved for some languages, "subtitle" becomes undefined

### ISSUE THREAD

**Issue by mateon1** [tomdionysus/foaas#145]
The separator made of punctuation gets broken for some languages (tested: i18n=es and i18n=pl)
As an example: http://www.foaas.com/you/Tom/Everyone?i18n=es, returns

```
{"message": "Jódete, Tom. !!,., !! - Todo el mundo ", "subtitle": " undefined"}
```

**Comment by gerardolm** [comment]
This is due to the "separator" variable as defined in the file foaas/lib/filters/i18n.coffee as "!!,.,!!"

I guess this separator is used to translate the message and subtitle in a single request. However, the translation service adds proper spaces to punctuation, so "!!,.,!!" becomes something else, and is thus not properly parsed in the response by the i18n filter.

**Comment by tomdionysus** [comment]
Same issue as #199 - translator service is a bit shit anyway and I should probably drop it
